version: "3"
services:
  job-portal:
    build:
      context: .
      dockerfile: build/docker/dev/Dockerfile
    volumes:
      - ./:/app/
    restart: on-failure
    depends_on:
      - postgresql
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.${APP_NAME}.rule=PathPrefix(`${PATH_PREFIX}`)"
    #   - "traefik.http.routers.${APP_NAME}.entrypoints=http"
    #   - "traefik.http.routers.${APP_NAME}.service=${APP_NAME}"
    #   - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=3000"
    ports:
      - 4000:4000
    environment:
      APP_ADDRESS: ":3000"
      APP_JWT_SECRET: bDHz544I7VX9gcPoi5lJiuqKGygUBRYPgxXcRIMZ3Qg
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}

  postgresql:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql/data
